spring:
  config:
    import: "optional:configserver:http://j9c211.p.ssafy.io:62110" #config server uri
  cloud:
    config:
      name: member
      profile: local

  jpa:
    hibernate:
      ddl-auto: create

encrypt:
  key: ${ssh-encrypt-key}
