spring:
  config:
    import: "optional:configserver:http://j9c211.p.ssafy.io:62110" #config server uri
  cloud:
    config:
      name: mydata
      profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

encrypt:
  key: ${ssh-encrypt-key}